### ISSUE TITLE
Deactivate Notifications

### ISSUE THREAD

**Issue by simi1030** [SlidePilot/SlidePilot-macOS#28]
### Feature description
macOS automatically disables notifications when the display is being mirrored. However, one feature of SlidePilot is the possible use two monitors and in this case notifications are not disabled, as far as I know. Notifications are still shown at the presenter monitor and may distract during presentation. 

It would be great if SlidePilot temporarily deactivates all macOS notification's by enabling `Do Not Disturb`.

### Problems this feature would solve
Displaying of notifications while presenting.

**Comment by columbbus** [comment]
I think it would be good to make this a feature you can opt-in in the preferences. Since you maybe wondering why there are no notifications coming through when SlidePilot is not open and you don't know about this feature.

**Comment by columbbus** [comment]
So I've tried to implement this, but there is not really an official API to do so. So I needed to implement some hacking to accomplish turning on/off Do Not Disturb (see this thread: https://stackoverflow.com/q/25210120/3272409).

However I've noticed that turning on/off Do Not Disturb using these methods will reset the preferences you've set for Do Not Disturb (the start and end times) and after doing that I was not able to set the end time anymore, not even in the preferences.

That of course is a no-go and I don't want to implement a feature that breaks your preferences because it's not using official API's.

The solution using the Apple Script didn't work for me. So I will maybe take a look at implementing this feature later, but it won't make it into this release. That's why I am closing it for now.
